### ISSUE TITLE
Make "Upcoming Deadlines" two rowed

### ISSUE THREAD

**Issue by sbogh** [CSE-210-Team-10/cse210-group10#148]
Task
- Make upcoming deadlines 2 rowed (bolded row for dates, regular row for tasks based on user feedback

Example:
![image](https://github.com/user-attachments/assets/d529a462-4ca2-46ae-a426-88db5c12bd7e)

Deliverables
- Styling changes to reflect above task

Size Estimation: Small (< 2 hours)

**Comment by mottur** [comment]
Duplicate.
