### ISSUE TITLE
Make "Upcoming Deadlines" two rowed

### ISSUE THREAD

**Issue by shayan-boghani** [CSE-210-Team-10/cse210-group10#161]
Task
- Make upcoming deadlines 2 rowed (bolded row for dates, regular row for tasks based on user feedback

Example:
![394970834-d529a462-4ca2-46ae-a426-88db5c12bd7e](https://github.com/user-attachments/assets/ee127c39-9291-440e-a41f-9ce5aa2894e2)

Deliverables
- Styling changes to reflect above task

Size Estimation: Small (< 2 hours)

**Comment by mottur** [comment]
Duplicate.
